language: java
sudo: false
install: true

services:
  - docker

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11

env:
  - DOCKER_FILE=/docker/arm/Dockerfile DOCKER_TAG=asck-survey-raspberry
  - DOCKER_FILE=/docker/x86/Dockerfile DOCKER_TAG=asck-survey
  - NONE=NONE

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: $SONAR_TOKEN
  apt:
    packages:
      - graphviz

jobs:   
  include:
    - stage: build and test
      # exclude combination of env with jdk
      env: NONE=NONE
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent compile sonar:sonar -Dsonar.projectKey=uniqueck_feedback-system
    - stage: build and deploy to docker hub
      if: branch = develop AND NOT type = pull_request
      jdk: openjdk11
      env: 
      - NONE=NONE
      # login to docker hub
      before_script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - mvn clean package -DskipTests=true
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
      - docker build --build-arg JAR_FILE=./target/asck-survey-*.jar -t $DOCKER_TAG -f $DOCKER_FILE .
      - docker images
      - docker tag $DOCKER_TAG $DOCKER_USERNAME/$DOCKER_TAG
      - docker push $DOCKER_USERNAME/$DOCKER_TAG

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
