language: java
sudo: false
install: true

jdk:
  - openjdk11

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: $SONAR_TOKEN
      branches:
        - develop
        - feature/* 

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify