language: java
sudo: false
install: true

services:
  - docker

jdk:
  - openjdk11

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: $SONAR_TOKEN
  apt:
    packages:
      - graphviz

script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=uniqueck_feedback-system
 - docker build  --build-arg JAR_FILE=./target/asck-survey-*.jar --tag uniqueck/asck-survey .
 - docker push uniqueck/asck-survey:latest
 
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify