language: java
sudo: false
install: true

services:
  - docker

jdk:
  - openjdk11

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: $SONAR_TOKEN
  apt:
    packages:
      - graphviz

jobs:
  include:
    - stage: build
      script: mvn clean package -DskipTest=true
    - stage: build docker
      # prepare qemu
      before_script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      script:
      - docker build --build-arg JAR_FILE=./target/asck-survey*.jar --tag uniqueck/asck-survey-raspberry -f ./docker/arm/Dockerfile .
      - docker build --build-arg JAR_FILE=./target/asck-survey*.jar --tag uniqueck/asck-survery -f ./docker/x86/Dockerfile .
    - stage: unit test
      script: mvn test
    - stage: QS & metrics
      script: mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=uniqueck_feedback-system
    - stage: deploy to docker hub
      if: branch = develop AND NOT type = pull_request
      # login to docker hub
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: 
      - docker push uniqueck/asck-survey
      - docker push uniqueck/asck-survey-raspberry

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
